description: Blog pribadi Ook Rahmawan mengulas tentang pengalaman kehidupan sehari-hari, jalan-jalan, wisata kuliner, makan enak serta hal menarik lainnya.
permalink: /:title
title: Ook Rahmawan
name: Ook Rahmawan
logo: Ook
excerpt_separator: <!--more-->
google_analytics: UA-180699504-1
author_name: Ook Rahmawan
author_first_name: Ook
author_last_name: Rahmawan
email: ookrahmawan@mail.ru
image: /img/logo/android-chrome-192x192.png
img_width: 400
img_height: 400
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
  envs: [local]
  blanklines: false
  profile: false
  startings: []
