description: Blog Pribadi Ook Rahmawan
permalink: /:title
title: Ook Rahmawan
name: Ook Rahmawan
compress_html:
  clippings: all
  comments: []
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
