description: Blog pribadi Ook Rahmawan mengulas tentang kehidupan sehari-hari, jalan-jalan, wisata kuliner dan makan enak serta hal menarik lainnya.
permalink: /:title
title: Ook Rahmawan
name: Ook Rahmawan
logo: Ook
google_analytics: UA-180699504-1
author_name: Ook Rahmawan
author_first_name: Ook
author_last_name: Rahmawan
email: ookrahmawan@mail.ru
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
  envs: [local]
  blanklines: false
  profile: false
  startings: []
