description: Blog pribadi Ook Rahmawan mengulas tentang kehidupan sehari-hari, jalan-jalan, wisata kuliner dan makan enak serta hal menarik lainnya.
permalink: /:title
title: Ook Rahmawan
name: Ook Rahmawan
logo: OR
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
  envs: [local]
  blanklines: false
  profile: false
  startings: []
