description: Blog pribadi Ook Rahmawan
permalink: /:title
title: Ook Rahmawan
name: Ook Rahmawan
logo: OR
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
